[build]
  command = "npm run build:netlify"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/database/migrations/*.sql", "src/data/*.json"]

[dev]
  command = "npm run dev:remote"
  targetPort = 5173
  port = 8888

[[redirects]]
  from = "/kid-a"
  to = "/"
  status = 301

[[redirects]]
  from = "/kid-a/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
